DELETE http://localhost:8080/api/blogs/6762cd023b64700c0ed7fe40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1aGE2NjY2NjYiLCJpZCI6IjY3NjE3MjQ2M2I1ZjMwYjMzNTBkM2VlZSIsImlhdCI6MTczNzM2OTEwOSwiZXhwIjoxNzM3MzcyNzA5fQ.TPqE3a3iEGbQQxvPDlFNHt7Vcw7SwsCorrkn3uwKVlY