POST http://localhost:8080/api/blogs
Content-Type: application/json

{
    "title": "testi",
    "author": "Saapa naha toimiiko",
    "url": "www.toimiiko.tama",
    "userId": "676172463b5f30b3350d3eee"
}